In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [7]:
from sklearn.datasets import load_iris

data=load_iris()

dir(data)
X=data.data
y=data.target
X,y

X.shape

(150, 4)

In [28]:
class LoadIrisv0(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1=nn.Linear(in_features=4,out_features=10)
        self.layer2=nn.Linear(in_features=10,out_features=20)
        self.layer3=nn.Linear(in_features=20,out_features=3)
        self.relu=nn.ReLU()
    def forward(self,x):
        x=self.relu(self.layer1(x))
        x=self.relu(self.layer2(x))
        x=self.layer3(x)
        
        return x


In [29]:
model_0=LoadIrisv0()
model_0

LoadIrisv0(
  (layer1): Linear(in_features=4, out_features=10, bias=True)
  (layer2): Linear(in_features=10, out_features=20, bias=True)
  (layer3): Linear(in_features=20, out_features=3, bias=True)
  (relu): ReLU()
)

In [18]:
import torch.nn as nn

In [5]:
import torch 
from torch import nn

In [30]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [32]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [58]:
X_train=torch.tensor(X_train,dtype=torch.float32)
X_test=torch.tensor(X_test,dtype=torch.float32)
y_train=torch.tensor(y_train,dtype=torch.float32)
y_train=torch.tensor(y_train,dtype=torch.float32)

res=model_0(X_train)
res.shape
res

y_logits=res
y_pred=torch.argmax(torch.softmax(y_logits,dim=1),dim=1)
y_pred.shape


/tmp/ipykernel_35/1802264216.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train=torch.tensor(X_train,dtype=torch.float32)
/tmp/ipykernel_35/1802264216.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test=torch.tensor(X_test,dtype=torch.float32)
/tmp/ipykernel_35/1802264216.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train=torch.tensor(y_train,dtype=torch.long)
/tmp/ipykernel_35/1802264216.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clon

torch.Size([120])

In [48]:
loss=nn.CrossEntropyLoss()

optimizer=torch.optim.Adam(params=model_0.parameters(),lr=0.01)


In [71]:
epochs=100

for epoch in range(epochs):
    model_0.train()
    y_logits=model_0(X_train)
    loss_train=loss_fn(y_logits,y_train)
    # y_pred=torch.softmax(y_logits, dim=1)
    y_pred=torch.argmax(y_logits, dim=1)
    
    acc1=accuracy_fn(y_pred,y_train)
    optimizer.zero_grad()
    loss_train.backward()
    optimizer.step()
    model_0.eval()
    
    with torch.inference_mode():
        y_logits=model_0(X_test)
        loss_test=loss_fn(y_logits,y_test)
        # y_pred=torch.softmax(y_logits, dim=1)
        y_pred=torch.argmax(y_logits, dim=1)
        
        acc2=accuracy_fn(y_pred,y_test)
        
    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs}|"
              f"Train loss:{loss_train:.4f}| Train acc: {acc1:.2f}% | "
              f"Test loss:{loss_test:.4f}| Test acc: {acc2:.2f}%")
    
    

Epoch 10/100|Train loss:0.0480| Train acc: 98.33% | Test loss:0.0230| Test acc: 100.00%
Epoch 20/100|Train loss:0.0479| Train acc: 98.33% | Test loss:0.0224| Test acc: 100.00%
Epoch 30/100|Train loss:0.0478| Train acc: 98.33% | Test loss:0.0218| Test acc: 100.00%
Epoch 40/100|Train loss:0.0477| Train acc: 98.33% | Test loss:0.0218| Test acc: 100.00%
Epoch 50/100|Train loss:0.0476| Train acc: 98.33% | Test loss:0.0215| Test acc: 100.00%
Epoch 60/100|Train loss:0.0475| Train acc: 98.33% | Test loss:0.0215| Test acc: 100.00%
Epoch 70/100|Train loss:0.0481| Train acc: 98.33% | Test loss:0.0238| Test acc: 100.00%
Epoch 80/100|Train loss:0.0486| Train acc: 98.33% | Test loss:0.0200| Test acc: 100.00%
Epoch 90/100|Train loss:0.0477| Train acc: 98.33% | Test loss:0.0198| Test acc: 100.00%
Epoch 100/100|Train loss:0.0474| Train acc: 98.33% | Test loss:0.0198| Test acc: 100.00%


In [51]:
def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item() # torch.eq() calculates where two tensors are equal
    acc = (correct / len(y_pred)) * 100 
    return acc

In [57]:
# Ensure all tensors have correct types
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)  # Targets must be long integers
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.long)

# Training loop
epochs = 100

for epoch in range(epochs):
    # Training phase
    model_0.train()
    
    # 1. Forward pass
    train_logits = model_0(X_train)
    
    # 2. Calculate loss (using raw logits)
    train_loss = loss_fn(train_logits, y_train)  # CrossEntropyLoss wants logits
    
    # 3. Calculate accuracy
    train_pred = torch.argmax(train_logits, dim=1)  # Convert to class predictions
    train_acc = accuracy_fn(y_train, train_pred)
    
    # 4. Backpropagation
    optimizer.zero_grad()
    train_loss.backward()
    optimizer.step()
    
    # Evaluation phase
    model_0.eval()
    with torch.inference_mode():
        # 1. Forward pass
        test_logits = model_0(X_test)
        
        # 2. Calculate test loss
        test_loss = loss_fn(test_logits, y_test)
        
        # 3. Calculate test accuracy
        test_pred = torch.argmax(test_logits, dim=1)
        test_acc = accuracy_fn(y_test, test_pred)
    
    # Print progress
    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs} | "
              f"Train Loss: {train_loss.item():.4f} | Train Acc: {train_acc:.2f}% | "
              f"Test Loss: {test_loss.item():.4f} | Test Acc: {test_acc:.2f}%")

/tmp/ipykernel_35/1660800342.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train = torch.tensor(X_train, dtype=torch.float32)
/tmp/ipykernel_35/1660800342.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train = torch.tensor(y_train, dtype=torch.long)  # Targets must be long integers
/tmp/ipykernel_35/1660800342.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test = torch.tensor(X_test, dtype=torch.float32)


Epoch 10/100 | Train Loss: 0.7909 | Train Acc: 70.83% | Test Loss: 0.7324 | Test Acc: 73.33%
Epoch 20/100 | Train Loss: 0.4289 | Train Acc: 95.83% | Test Loss: 0.4022 | Test Acc: 100.00%
Epoch 30/100 | Train Loss: 0.2323 | Train Acc: 97.50% | Test Loss: 0.2255 | Test Acc: 100.00%
Epoch 40/100 | Train Loss: 0.1127 | Train Acc: 98.33% | Test Loss: 0.1229 | Test Acc: 100.00%
Epoch 50/100 | Train Loss: 0.0759 | Train Acc: 98.33% | Test Loss: 0.0800 | Test Acc: 100.00%
Epoch 60/100 | Train Loss: 0.0655 | Train Acc: 98.33% | Test Loss: 0.0624 | Test Acc: 100.00%
Epoch 70/100 | Train Loss: 0.0617 | Train Acc: 98.33% | Test Loss: 0.0546 | Test Acc: 100.00%
Epoch 80/100 | Train Loss: 0.0597 | Train Acc: 98.33% | Test Loss: 0.0501 | Test Acc: 100.00%
Epoch 90/100 | Train Loss: 0.0583 | Train Acc: 98.33% | Test Loss: 0.0461 | Test Acc: 100.00%
Epoch 100/100 | Train Loss: 0.0572 | Train Acc: 97.50% | Test Loss: 0.0430 | Test Acc: 100.00%


In [77]:
test_logits = model_0(X_test)
train_pred = torch.argmax(test_logits, dim=1)
train_pred ,y_test



(tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
         2, 2, 2, 2, 0, 0]),
 tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
         2, 2, 2, 2, 0, 0]))

***Save model***


In [78]:
from pathlib import Path

# Create models directory (if it doesn't already exist), see: https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir
MODEL_PATH = Path("models")
MODEL_PATH.mkdir(parents=True, # create parent directories if needed
                 exist_ok=True # if models directory already exists, don't error
)

# Create model save path
MODEL_NAME = "03_pytorch_classification_model_2.pth"
MODEL_SAVE_PATH = MODEL_PATH / MODEL_NAME

# Save the model state dict
print(f"Saving model to: {MODEL_SAVE_PATH}")
torch.save(obj=model_0.state_dict(), # only saving the state_dict() only saves the learned parameters
           f=MODEL_SAVE_PATH)

Saving model to: models/03_pytorch_classification_model_2.pth


***Load saved model***

In [84]:
import torch
from torch import nn

class LoadIrisv1(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(4, 10)
        self.layer2 = nn.Linear(10, 20)
        self.layer3 = nn.Linear(20, 3)
        self.relu = nn.ReLU()
    
    def forward(self, x):
        x = self.relu(self.layer1(x))
        x = self.relu(self.layer2(x))
        x = self.layer3(x)
        return x

# 2. Create an instance of your model
model = LoadIrisv1()

# 3. Load the saved state dictionary
model_path = "models/03_pytorch_classification_model_2.pth"
model.load_state_dict(torch.load(model_path))

# 4. Set to evaluation mode
model.eval()

# Now your model is ready for inference!

torch.argmax(model(X_test),dim=1),y_test


(tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
         2, 2, 2, 2, 0, 0]),
 tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
         2, 2, 2, 2, 0, 0]))